### ISSUE TITLE
Add Projects

### ISSUE THREAD

**Issue by Ishaan28malik** [Ctrl-Alt-Contributors/Projects-#1]
Provide some projects from your side that you think are beneficial to start with or you want to learn :snowman:

**You can also bring Projects if you are stuck somewhere in any projects or you want to improve them**
:

**Comment by harsh-2711** [comment]
@Ishaan28malik and all team members, I am currently working on ML based solutions for compressing a text file with compression ratio of about 5:1. I have further plans after completing the compression part. If anyone wants to help, just ping me. I have successfully reached a stage of compressing a text article to a qr code.

**Comment by Ishaan28malik** [comment]
Great let's wait for rest of them to be active @harsh-2711
